### ISSUE TITLE
random-uuid 

### ISSUE THREAD

**Issue by ioRekz** [rauhs/klang#3]
I'm trying to setup a basic logging so I just followed the usage section and I have an error 
at (random-uuid) when calling default-config.

Looking at the code I don't get where this should come from

**Comment by rauhs** [comment]
What's the exact error? I'm unable to reproduce it. Is it a "redefined error"?

**Comment by ioRekz** [comment]
undefined error but random-uuid is never defined in core.cljs
maybe after this a742337619d91cd9e1f81022b82aa312e2b58284 ?

**Comment by rauhs** [comment]
`random-uuid` got added to Clojurescript 1.7.Something. So you'll need a new Clojurescript. What version of cljs are you using?

**Comment by ioRekz** [comment]
Ho ok, I'm using reagent 0.5.0 which is pulling an older cljs version, I'm
updating. Thanks !

**Comment by rauhs** [comment]
Glad it's all working. Should probably mention it.
Cheers
