### ISSUE TITLE
Feature request, bind ESC to close of klang overlay

### ISSUE THREAD

**Issue by PEZ** [rauhs/klang#6]
I'd like to be able to close the klang overlay using the ESC key. Ideally it would open with the search box focused so that I could open the overlay, type to start searching and close using the ESC key.

If you think it is an idea worth trying out I could try implementing it in a pull request.

**Comment by rauhs** [comment]
PR welcome! The autofocus is easy with `:auto-focus` set to `true`. I use that in my other code. ESC should def close the overlay.

**Comment by PEZ** [comment]
I'll give it a shot. How do you go about developing in this project? I can't figure out how to test that my changes work. Just knowing what commands you run and what you do to get feedback on your changes will do. =)

**Comment by rauhs** [comment]
I just pushed a commit that adds figwheel. Now you can just run `lein figwheel` and the demo will come up. Let me know if that works for you.

**Comment by PEZ** [comment]
Fixed by #7.
